// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG7u0uNGufUdSG6vEDA2e_vfjpzhGn6V4',
    appId: '1:516146818933:web:c5230380068b9572156d3c',
    messagingSenderId: '516146818933',
    projectId: 'horas-v3-a455e',
    authDomain: 'horas-v3-a455e.firebaseapp.com',
    storageBucket: 'horas-v3-a455e.appspot.com',
    measurementId: 'G-LRYYDGLLQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtrpDt3nZNu0z95RHg27CmHqF80SGmXeQ',
    appId: '1:516146818933:android:f61e4889bdc180c9156d3c',
    messagingSenderId: '516146818933',
    projectId: 'horas-v3-a455e',
    storageBucket: 'horas-v3-a455e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDkYW_g58Df86eDPW2RycIjS21iYlynxw',
    appId: '1:516146818933:ios:a3900132ae41bd16156d3c',
    messagingSenderId: '516146818933',
    projectId: 'horas-v3-a455e',
    storageBucket: 'horas-v3-a455e.appspot.com',
    iosClientId: '516146818933-2acncv542d9qjr57v45eahk6cv3dmci1.apps.googleusercontent.com',
    iosBundleId: 'com.example.primeiroApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG7u0uNGufUdSG6vEDA2e_vfjpzhGn6V4',
    appId: '1:516146818933:web:4d052d583893dd4d156d3c',
    messagingSenderId: '516146818933',
    projectId: 'horas-v3-a455e',
    authDomain: 'horas-v3-a455e.firebaseapp.com',
    storageBucket: 'horas-v3-a455e.appspot.com',
    measurementId: 'G-HHC3TL1T7G',
  );

}